services:
  backend:
    build: .
    volumes:
      - type: bind
        source: ./target/classes
        target: /app/target/classes
      - type: bind
        source: ./target/test-classes
        target: /app/target/test-classes
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/issue-tracker
      SPRING_DATASOURCE_USERNAME: issuetracker
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    user: postgres
    image: postgres:latest
    volumes:
      - ./src/main/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: issuetracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: issue-tracker