services:
  backend:
    build: .
    volumes:
      - type: bind
        source: ./target/classes
        target: /app/target/classes
      - type: bind
        source: ./target/test-classes
        target: /app/target/test-classes
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/issue-tracker
      SPRING_DATASOURCE_USER: issuetracker
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_PROFILES_ACTIVE: dev
      SPRING_SQL_INIT_MODE: always
  postgres:
    user: postgres
    image: postgres:latest
    volumes:
      - /var/lib/postgres/data
    environment:
      POSTGRES_USER: issuetracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: issue-tracker