CREATE TYPE issue_status AS ENUM ('open', 'in progress', 'more info needed', 'resolved');

CREATE TYPE issue_priority AS ENUM ('high', 'medium', 'low');

CREATE TABLE issue (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(128) NOT NULL,
    description TEXT NOT NULL,
    status issue_status NOT NULL,
    priority issue_priority NOT NULL,
    submitter_id VARCHAR(128),
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL
);

CREATE TABLE issue_assignee (
    issue_id INTEGER REFERENCES issue (id) ON DELETE CASCADE ON UPDATE CASCADE,
    user_id VARCHAR(128),
    PRIMARY KEY (issue_id, user_id)
);
